version: '3.8'

services:
  antink-server:
    build: ./soal_3
    container_name: antink-server
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./it24_host:/it24_host
      - antink_mount:/antink_mount
      - ./antink-logs:/var/log

  antink-logger:
    image: ubuntu
    container_name: antink-logger
    volumes:
      - ./antink-logs:/var/log
    command: tail -f /var/log/it24.log

volumes:
  antink_mount:
